[package]
name = "kbb"
version = "0.1"
lean_version = "nightly-2018-06-21"
path = "src"

[dependencies]
mathlib = {git = "git@github.com:leanprover-community/mathlib.git", rev = "a770ee5a5a46973494b2ad41e672e21cecba4471"}
