[package]
name = "kbb"
version = "0.1"
lean_version = "nightly-2018-06-21"
path = "src"

[dependencies]
mathlib = {git = "git@github.com:leanprover-community/mathlib.git", rev = "f10e7adbedb01d95dfed407f8fcf76ce6329cbf8"}
